export const UserTypes = {
  // fetch userDetails
  FETCH_USER_DETAILS: "FETCH_USER_DETAILS",
  REQUEST_USER_DETAILS: "REQUEST_USER_DETAILS",
  SUCCESS_USER_DETAILS: "SUCCESS_USER_DETAILS",
  FAILURE_USER_DETAILS: "FAILURE_USER_DETAILS",

  // update userDetails
  UPDATE_USER_DATA: "UPDATE_USER_DATA",
  REQUEST_UPDATE_USER_DATA: "REQUEST_UPDATE_USER_DATA",
  SUCCESS_UPDATE_USER_DATA: "SUCCESS_UPDATE_USER_DATA",
  FAILURE_UPDATE_USER_DATA: "FAILURE_UPDATE_USER_DATA",

  // delete userDetails
  DELETE_USER_DETAILS: "DELETE_USER_DETAILS",
  REQUEST_DELETE_USER_DETAILS: "REQUEST_DELETE_USER_DETAILS",
  SUCCESS_DELETE_USER_DETAILS: "SUCCESS_DELETE_USER_DETAILS",
  FAILURE_DELETE_USER_DETAILS: "FAILURE_DELETE_USER_DETAILS",

  // create userDetails
  FETCH_CREATE_USER_DETAILS: "FETCH_CREATE_USER_DETAILS",
  REQUEST_CREATE_USER_DETAILS: "REQUEST_CREATE_USER_DETAILS",
  SUCCESS_CREATE_USER_DETAILS: "SUCCESS_CREATE_USER_DETAILS",
  FAILURE_CREATE_USER_DETAILS: "FAILURE_CREATE_USER_DETAILS",
};
